import PptxGenJS from "pptxgenjs";
import type { SlideContent } from "./notebooklm";
import type { ReportMode } from "./prompts";
import { MODES } from "./prompts";

const COLORS = {
	primary: "2B579A",
	secondary: "4472C4",
	accent: "ED7D31",
	text: "333333",
	lightBg: "F2F2F2",
	white: "FFFFFF",
};

const MODE_COLORS: Record<ReportMode, { primary: string; accent: string }> = {
	detailed: { primary: "2B579A", accent: "ED7D31" },
	executive: { primary: "1A1A2E", accent: "E94560" },
	easy: { primary: "2D6A4F", accent: "52B788" },
};

export async function generatePptx(
	title: string,
	source: string,
	summary: string,
	slides: SlideContent[],
	mode: ReportMode
): Promise<Buffer> {
	const pres = new PptxGenJS();
	const modeConfig = MODES[mode];
	const colors = MODE_COLORS[mode];

	pres.layout = "LAYOUT_WIDE";
	pres.author = "Clippings PPT Generator";
	pres.subject = title;

	// 표지 슬라이드
	const coverSlide = pres.addSlide();
	coverSlide.background = { color: colors.primary };
	coverSlide.addText(`${modeConfig.icon} ${modeConfig.label}`, {
		x: 0.8,
		y: 0.5,
		w: 11.5,
		h: 0.6,
		fontSize: 14,
		color: colors.accent,
		bold: true,
	});
	coverSlide.addText(title, {
		x: 0.8,
		y: 1.5,
		w: 11.5,
		h: 2,
		fontSize: 36,
		bold: true,
		color: COLORS.white,
		align: "left",
		valign: "middle",
	});
	if (source) {
		coverSlide.addText(source, {
			x: 0.8,
			y: 3.8,
			w: 11.5,
			h: 0.6,
			fontSize: 12,
			color: COLORS.white,
			align: "left",
			italic: true,
		});
	}
	coverSlide.addText("Generated by Clippings PPT Generator", {
		x: 0.8,
		y: 6.5,
		w: 11.5,
		h: 0.4,
		fontSize: 10,
		color: COLORS.white,
		align: "right",
	});

	// 요약 슬라이드
	if (summary) {
		const summarySlide = pres.addSlide();
		summarySlide.addText(mode === "executive" ? "Executive Summary" : "요약", {
			x: 0.8,
			y: 0.4,
			w: 11.5,
			h: 0.8,
			fontSize: 28,
			bold: true,
			color: colors.primary,
		});
		summarySlide.addShape(pres.ShapeType.rect, {
			x: 0.8,
			y: 1.2,
			w: 11.5,
			h: 0.04,
			fill: { color: colors.accent },
		});
		summarySlide.addText(summary, {
			x: 0.8,
			y: 1.6,
			w: 11.5,
			h: 5,
			fontSize: 16,
			color: COLORS.text,
			lineSpacingMultiple: 1.5,
			valign: "top",
		});
	}

	// 내용 슬라이드들
	for (const slide of slides) {
		const contentSlide = pres.addSlide();

		contentSlide.addText(slide.title, {
			x: 0.8,
			y: 0.4,
			w: 11.5,
			h: 0.8,
			fontSize: 24,
			bold: true,
			color: colors.primary,
		});

		contentSlide.addShape(pres.ShapeType.rect, {
			x: 0.8,
			y: 1.2,
			w: 11.5,
			h: 0.04,
			fill: { color: colors.accent },
		});

		if (slide.bullets.length > 0) {
			const bulletText = slide.bullets.map((b) => ({
				text: b,
				options: {
					fontSize: 16,
					color: COLORS.text,
					bullet: { code: "2022" },
					lineSpacingMultiple: 1.8,
					paraSpaceAfter: 6,
				},
			}));

			contentSlide.addText(bulletText, {
				x: 1.0,
				y: 1.6,
				w: 11,
				h: 5,
				valign: "top",
			});
		}
	}

	const data = await pres.write({ outputType: "nodebuffer" });
	return data as Buffer;
}
